"""BI enterprise models: KPI definitions + KPI snapshots.

Own tables only. Shared ``Base`` is imported, never redefined; the single
alembic revision is generated by master from the DDL spec in ``docs/bi.md``.
"""
from __future__ import annotations

from datetime import datetime, timezone

from sqlalchemy import JSON, Boolean, DateTime, Float, Integer, String
from sqlalchemy.orm import Mapped, mapped_column

from app.database.connection import Base

__all__ = ["KpiDefinition", "KpiSnapshot"]


def _utcnow() -> datetime:
    return datetime.now(timezone.utc)


class KpiDefinition(Base):
    """Named KPI with formula description, target and warn/crit thresholds."""

    __tablename__ = "kpi_definitions"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    name: Mapped[str] = mapped_column(String(128), unique=True, index=True)
    description: Mapped[str] = mapped_column(String(1024), default="")
    formula: Mapped[str] = mapped_column(String(1024), default="")
    unit: Mapped[str] = mapped_column(String(32), default="")
    target: Mapped[float | None] = mapped_column(Float, nullable=True)
    warn_threshold: Mapped[float | None] = mapped_column(Float, nullable=True)
    crit_threshold: Mapped[float | None] = mapped_column(Float, nullable=True)
    higher_is_better: Mapped[bool] = mapped_column(Boolean, default=True)
    is_active: Mapped[bool] = mapped_column(Boolean, default=True)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=_utcnow)
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=_utcnow, onupdate=_utcnow
    )


class KpiSnapshot(Base):
    """One computed KPI value persisted for history / automated reports."""

    __tablename__ = "kpi_snapshots"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    kpi_name: Mapped[str] = mapped_column(String(128), index=True)
    value: Mapped[float] = mapped_column(Float, default=0.0)
    target: Mapped[float | None] = mapped_column(Float, nullable=True)
    status: Mapped[str] = mapped_column(String(16), default="ok")
    period: Mapped[str] = mapped_column(String(32), default="")
    filters: Mapped[dict] = mapped_column(JSON, default=dict)
    meta: Mapped[dict] = mapped_column(JSON, default=dict)
    computed_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=_utcnow)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=_utcnow)
